controller_manager:
  ros__parameters:
    update_rate: 100 #active controller update rate in Hz

joint_state_broadcaster:
  ros__parameters:
    type: joint_state_broadcaster/JointStateBroadcaster
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
  #loads the joint state broadcaster, which publishes joint states (like position, velocity) to /joint_states

position_controller:
  ros__parameters:
    type: position_controllers/JointPositionController
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
    state_publish_rate: 50
  #Loads the position controller, a type of ROS 2 controller that sends commands 
  #to actuate joints to desired positions, and publishes its internal state at 50 Hz.